# Generated by Django 3.2.8 on 2021-10-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initem',
            name='name',
        ),
        migrations.AddField(
            model_name='initem',
            name='procesesed',
            field=models.BooleanField(default=False),
        ),
    ]
