# Generated by Django 3.2.8 on 2021-10-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuff', '0002_auto_20211016_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='initem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.customuser'),
            preserve_default=False,
        ),
    ]
