# Generated by Django 3.2.8 on 2021-10-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_alter_initem_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initem',
            old_name='procesesed',
            new_name='processed',
        ),
    ]
